AFFISE-17459 - two ways to resolve
clobucks/grpc-consul-resolver pull request #7
Opened 2022-04-01 08:13 UTC by hesidoryn

2022-04-01 09:10 UTC, komex requested changes

2022-04-01 09:10 UTC, komex commented on builder.go
> +		r.resolveWithPeriod(cli, tgt)
Это нужно запустить в отдельной горутине, т.к. `RunWithClientAndHclog` - блокирующая операция.

2022-04-01 09:10 UTC, komex commented on builder.go
> +		addresses := make([]resolver.Address, 0, len(resp))
Никак нельзя переиспользовать метод `fillAddresses`?

2022-04-01 09:10 UTC, komex commented on builder.go
> +		logger.WithValues("new_addresses", len(addresses)).Info("applying changes")
И как часто будем в логи писать?

2022-04-01 09:10 UTC, komex commented on builder.go
> +		r.cc.UpdateState(resolver.State{Addresses: addresses})
Если запустим этот метод в отдельной горутине, то нужно как-то синхронизировать потоки.

2022-04-01 09:13 UTC, hesidoryn commented on builder.go
> +		addresses := make([]resolver.Address, 0, len(resp))
ответы у watcher и Service разные, поэтому скопировал логику

2022-04-01 09:13 UTC, hesidoryn commented on builder.go
> +		r.resolveWithPeriod(cli, tgt)
точно, спасибо

2022-04-04 08:09 UTC, hesidoryn commented on builder.go
> +		r.cc.UpdateState(resolver.State{Addresses: addresses})
добавил мьютекс

2022-04-04 08:10 UTC, hesidoryn commented on builder.go
> +		logger.WithValues("new_addresses", len(addresses)).Info("applying changes")
я бы оставил пока на время теста. если успешно всё будет, то удалю

2022-04-04 08:38 UTC, komex approved these changes

2022-04-04 09:41 UTC, komex commented on builder.go
> +		t.Period = time.Duration(time.Minute)
Вроде приведение лишнее. time.Minute - уже имеет нужный тип.

2022-04-04 09:52 UTC, hesidoryn commented on builder.go
> +		t.Period = time.Duration(time.Minute)
поправил

2022-04-04 13:00 UTC, merged